CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) NOT NULL,
  role VARCHAR(20) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  deleted TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_behavior (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  keyword VARCHAR(255),
  item_id VARCHAR(128),
  item_type VARCHAR(32),
  tags VARCHAR(512),
  duration_seconds INT DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_behavior_user (user_id),
  INDEX idx_behavior_type (item_type)
);

CREATE TABLE IF NOT EXISTS user_profile (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
  interest_tags VARCHAR(1024),
  preferred_types VARCHAR(255),
  deleted TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS search_source (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL UNIQUE,
  type VARCHAR(32) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  weight DOUBLE NOT NULL DEFAULT 1,
  authority_score DOUBLE NOT NULL DEFAULT 0.7,
  config_json TEXT,
  deleted TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS search_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  external_id VARCHAR(128) NOT NULL,
  type VARCHAR(32) NOT NULL,
  source_name VARCHAR(80),
  title VARCHAR(255) NOT NULL,
  summary TEXT,
  url VARCHAR(512),
  thumbnail_url VARCHAR(512),
  tags VARCHAR(512),
  authority_score DOUBLE DEFAULT 0.7,
  published_at DATETIME,
  deleted TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_search_item_type (type),
  INDEX idx_search_item_external (external_id)
);

CREATE TABLE IF NOT EXISTS hot_recommendation (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  type VARCHAR(32) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT,
  url VARCHAR(512),
  thumbnail_url VARCHAR(512),
  heat_score DOUBLE DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1,
  deleted TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS search_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT,
  keyword VARCHAR(255),
  type VARCHAR(32),
  result_count INT DEFAULT 0,
  duration_ms BIGINT DEFAULT 0,
  source_distribution VARCHAR(512),
  deleted TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_search_log_user (user_id),
  INDEX idx_search_log_keyword (keyword)
);

CREATE TABLE IF NOT EXISTS ranking_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  relevance_weight DOUBLE NOT NULL DEFAULT 0.45,
  freshness_weight DOUBLE NOT NULL DEFAULT 0.20,
  authority_weight DOUBLE NOT NULL DEFAULT 0.25,
  preference_weight DOUBLE NOT NULL DEFAULT 0.10,
  enabled TINYINT NOT NULL DEFAULT 1,
  deleted TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
